msm8998: Remove timeservice_app_cert certificate
* This cert was removed in R qcom sepolicy...

[poad42]: use platform instead
error: vendor/oneplus/msm8998-common/Android.bp:265:1: "TimeService" depends on undefined module "timeservice_app_cert-legacy-um"

Change-Id: Iddd73a0c0a8bb9da224e62c262f7e6297772f152
Signed-off-by: NurKeinNeid <mralexman3000@gmail.com>

Former-commit-id: d854443cfff246a9a0e1a8e5737e7172d29cd396